params:
  seed: ${...seed}

  algo:
    name: cat_ddpg_demos_generate_continuous

  config:
    name: ${resolve_default:SoloParkour,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    total_timesteps: 2e8
    buffer_size: 4999680 # % (5 * 256) = 0
    batch_size: 512
    target_policy_path: "path/to/cleanrl_model.pt"
    demos_buffer_size: 1999360 # % (5 * 256) = 0
    horizon_length: 24 # 24 for t = 0.02 (decimation = 4)

    max_epochs: ${resolve_default:1000,${....max_iterations}}
